apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: ng-frontend
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 20
    labels:
      nodegroup: frontend
    ssh:
      allow: true
      publicKeyName: new_kp # Replace with your EC2 key pair name

  - name: ng-backend
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    labels:
      nodegroup: backend

