apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: backend-ns 
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
