apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  type: ClusterIP  # ClusterIP because it's accessed via Ingress
  selector:
    app: frontend
  ports:
    - port: 80  # Exposes port 80 on the service
      targetPort: 80  # Routes traffic to port 80 on the pods

