apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: frontend-ns
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/redirect-http-to-https: 'true'
spec:
  ingressClassName: alb
  tls:
  - hosts:
    - www.sunilcloud.online
    secretName: my-tls-secret
  rules:
  - host: www.sunilcloud.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

