apiVersion: v1
kind: Service
metadata:
  name: backend-service      # Name of service
  namespace: backend-ns 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:   #To define the desired condifuration for the service
  type: ClusterIP      # Type of service, use LoadBalancer or NodePort as pe req.
  selector:     #The selector tells the Service which Pods to route traffic to, based on labels.
    app: backend
  ports:        #defines how traffic is forwarded:
    - port: 5000  #The Service port, used internally in the cluster.
      targetPort: 5000    #The container port on the selected Pods to which traffic should be directed.
