apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traffic-from-frontend-ns
  namespace: backend-ns  # Apply this policy in the backend namespace
spec:
  podSelector: 
    matchLabels:
      app: backend  # Selects the backend pods
  ingress:
    - from:
        - namespaceSelector: 
            matchLabels:
              name: backend-ns  # Allow traffic from the `frontend-ns` namespace
      ports:
        - protocol: TCP
          port: 5000  # Allow traffic on port 5000

